service: lecture-9-api-gateway-sns
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  publishMessage:
    handler: handler.publishMessage
    events:
      - http:
          method: POST
          path: publishMessage
